// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfbbhopklpidevajunnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmYmJob3BrbHBpZGV2YWp1bm54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1OTIzMzgsImV4cCI6MjA3MDE2ODMzOH0.RRsHTEU4g1jTvgmZbRt6sCBVJBbYkRJfdAq1_qFk6eY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});